# Generated by Django 3.0.6 on 2020-05-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoa', '0002_auto_20200526_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titile',
            new_name='title',
        ),
    ]
